### ISSUE TITLE
Runtime exception log

### ISSUE THREAD

**Issue by solderzzc** [SharpAI/DeepCamera#14]
@lambda-zhang 
Do you know how to fix this issue:
```
[2019-03-14 02:15:57,181: WARNING/ForkPoolWorker-1] motion_detect: Error,
[2019-03-14 02:15:57,181: WARNING/ForkPoolWorker-1] OpenCV(4.0.0-pre) /data/data/com.termux/files/home/opencv/modules/core/src/arithm.cpp:665: error: (-215:Assertion failed) type2 == CV_64F && (sz2.height == 1 || sz2.height == 4) in function 'arithm_op'
[2019-03-14 02:15:57,181: WARNING/ForkPoolWorker-1] Performance: motion_detect is 0.00202393531799S
[2019-03-14 02:15:57,182: WARNING/ForkPoolWorker-1] motion_result=False, (-1, -1) image_path=/storage/emulated/0/Download/frame_14032019_021557_128.jpg
[2019-03-14 02:15:57,182: WARNING/ForkPoolWorker-1] save_static_image: not save, interval=4.18020915985
[device] tid: 1552529756550 person num: 0 face num: 0 cost: 71
[2019-03-14 02:15:57,234: INFO/ForkPoolWorker-1] Task upload_api-v2.detect[0b08125a-182d-4723-8329-4a5a42525cf5] succeeded in 0.0718838829998s: '{"totalPeople": 0, "detected": false, "totalmtcnn": null, "ts": 1552529757151, "cropped": []}'
[2019-03-14 02:15:57,330: INFO/ForkPoolWorker-1] Task upload_api-v2.extract_v2[913b5665-4077-476d-8d7e-2ef57606da8d] succeeded in 0.607800769998s: '{"embedding_path": ""}'
uncaughtException { Error: ENOENT: no such file or directory, open ''
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.writeFileSync (fs.js:1299:33)
    at Result.<anonymous> (/data/data/com.termux/files/home/runtime/main.bin.js:1:12132)
    at emitOne (events.js:116:13)
    at Result.emit (events.js:211:7)
    at RedisClient.<anonymous> (/data/data/com.termux/files/home/runtime/node_modules/node-celery/celery.js:180:21)
    at emitThree (events.js:136:13)
    at RedisClient.emit (events.js:217:7)
    at return_pub_sub (/data/data/com.termux/files/home/runtime/node_modules/redis/index.js:794:18)
    at RedisClient.return_reply (/data/data/com.termux/files/home/runtime/node_modules/redis/index.js:833:9) errno: -2, code: 'ENOENT', syscall: 'open', path: '' }
/storage/emulated/0/Download/frame_14032019_021557_422.jpg
```

I'm debugging on Rockpro64 Android 7.1.2.

**Comment by solderzzc** [comment]
Ijkplayer also quit:
```
2019-03-13 19:16:06.699 V/TextureRenderView: time diff (FD) 20
2019-03-13 19:16:06.699 D/TextureRenderView: recognition rect: RectF(525.9714, 141.7028, 830.4379, 495.22818)
2019-03-13 19:16:06.700 A/Bitmap: Error, cannot access an invalid/free'd bitmap here!
2019-03-13 19:16:06.701 A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 13338 (Thread-3)
```

**Comment by solderzzc** [comment]
```
2019-03-13 19:22:00.194 E/ActivityManager: Found activity ActivityRecord{1a02926 u0 tv.danmaku.ijk.media.example/.activities.VideoActivity t16 f} in proc activity list using null instead of expected ProcessRecord{2f75a57 13555:tv.danmaku.ijk.media.example/u0a57}
2019-03-13 19:22:00.195 E/lowmemorykiller: Error writing /proc/13555/oom_score_adj; errno=22
2019-03-13 19:22:00.195 W/ActivityManager: Failed setting process group of 13555 to 1
2019-03-13 19:22:00.195 W/System.err: java.lang.IllegalArgumentException: Given thread 13597 does not exist
2019-03-13 19:22:00.196 W/System.err:     at android.os.Process.setThreadPriority(Native Method)
2019-03-13 19:22:00.196 I/art: Background sticky concurrent mark sweep GC freed 34769(2MB) AllocSpace objects, 3(412KB) LOS objects, 16% free, 8MB/9MB, paused 5.254ms total 53.426ms
2019-03-13 19:22:00.197 W/System.err:     at com.android.server.am.ActivityManagerService.applyOomAdjLocked(ActivityManagerService.java:20773)
2019-03-13 19:22:00.197 W/System.err:     at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:21283)
2019-03-13 19:22:00.197 W/System.err:     at com.android.server.am.ActivityStack.resumeTopActivityInnerLocked(ActivityStack.java:2516)
2019-03-13 19:22:00.197 W/System.err:     at com.android.server.am.ActivityStack.resumeTopActivityUncheckedLocked(ActivityStack.java:2160)
2019-03-13 19:22:00.197 W/System.err:     at com.android.server.am.ActivityStackSupervisor.resumeFocusedStackTopActivityLocked(ActivityStackSupervisor.java:1833)
2019-03-13 19:22:00.197 W/System.err:     at com.android.server.am.ActivityStackSupervisor.resumeFocusedStackTopActivityLocked(ActivityStackSupervisor.java:1823)
2019-03-13 19:22:00.197 W/System.err:     at com.android.server.am.ActivityStack.finishCurrentActivityLocked(ActivityStack.java:3674)
2019-03-13 19:22:00.197 W/System.err:     at com.android.server.am.ActivityStack.handleAppCrashLocked(ActivityStack.java:5071)
2019-03-13 19:22:00.197 W/System.err:     at com.android.server.am.ActivityStackSupervisor.handleAppCrashLocked(ActivityStackSupervisor.java:2885)
2019-03-13 19:22:00.197 W/System.err:     at com.android.server.am.AppErrors.handleAppCrashLocked(AppErrors.java:606)
2019-03-13 19:22:00.197 W/System.err:     at com.android.server.am.AppErrors.makeAppCrashingLocked(AppErrors.java:493)
2019-03-13 19:22:00.197 W/System.err:     at com.android.server.am.AppErrors.crashApplicationInner(AppErrors.java:358)
2019-03-13 19:22:00.197 W/System.err:     at com.android.server.am.AppErrors.crashApplication(AppErrors.java:309)
2019-03-13 19:22:00.197 W/System.err:     at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:13704)
2019-03-13 19:22:00.197 W/System.err:     at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
2019-03-13 19:22:00.204 I/ActivityManager: Killing 13555:tv.danmaku.ijk.media.example/u0a57 (adj 100): crash
```

**Comment by solderzzc** [comment]
duplicated
